#!/bin/sh
# Preview script built for use with lf and fzf

handle() {
     case $(file --mime-type "$1" -bL) in 
         image/*|audio/*|video/*) mediainfo "$1";;
         *) highlight "$1" -O ansi --force;;
     esac
}

case "$1" in
     *.pdf) pdftotext "$1" -;;
     *.png|*.jpg|*.jpeg|*.mkv|*.mp3|*.mp4|*.m4v) mediainfo "$1";;
	*.tgz|*.tar.gz) tar tzf "$1";;
	*.tar.bz2|*.tbz2) tar tjf "$1";;
	*.tar.txz|*.txz) xz --list "$1";;
	*.tar) tar tf "$1";;
	*.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1";;
	*.rar) unrar l "$1";;
	*.7z) 7z l "$1";;
	*.[1-8]) man "$1" | col -b ;;
	*.o) nm "$1" | less ;;
	*.iso) iso-info --no-header -l "$1";;
	*odt,*.ods,*.odp,*.sxw) odt2txt "$1";;
	*.doc) catdoc "$1" ;;
	*.docx) docx2txt "$1" - ;;
	*.csv) cat "$1" | sed s/,/\\n/g ;;
     *) handle "$1" ;;
esac
